export const CRYPTO_CONSTANTS = {
  PBKDF2_ITERATIONS: 100000,
  SALT_LENGTH: 16,
  IV_LENGTH: 12, // Standard for GCM
  TAG_LENGTH_BITS: 128,
  ALGORITHM_AES: 'AES-GCM',
  ALGORITHM_KDF: 'PBKDF2',
  HASH_ALGO: 'SHA-256',
  KEY_LENGTH: 256
};

export const EXTENSION_ENCRYPTED = '.enc';
